baseURL = "http://example.org/"
languageCode = "en-us"
title = "osu! ruleset"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "HelloYeew"
  defaultImage = "default.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "http://github.com/HelloYeew/osu-ruleset-pages"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "HelloYeew"
     link = "https://helloyeew.dev"
