baseURL = "http://rulesets.info/"
languageCode = "en-us"
title = "rūrusetto"
theme = "hugo-cards"
paginate = 50

[params]
  builtBy = "Rūrusetto"
  defaultImage = "default.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "https://github.com/Rurusetto/rurusetto/"
  email = "contact@rulesets.info"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "Rūrusetto team"
     link = "https://github.com/Rurusetto"
