name: Deploy Changes to Server
on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd rurusetto/rurusetto
          git pull
          source myprojectenv/bin/activate
          cd wiki
          django-admin compilemessages
          cd ..
          cd users
          django-admin compilemessages
          cd ..
          cd ..
          pip install --upgrade --force-reinstall -r requirements.txt
          cd rurusetto
          python manage.py migrate
          python manage.py collectstatic --noinput --clear
          echo ${{ secrets.PASSWORD }} | sudo -S -k systemctl restart gunicorn.socket gunicorn.service
